# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false
  - task: DownloadSecureFile@1
    name: downloadMySecureFile
    displayName: downloadMySecureFile
    inputs:
      secureFile: 87172376-fb85-4803-8be0-68d0afa8f052
  - task: CopyFiles@2
    displayName: 'Copy .Env File to: Default Working Directory'
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: .env.reporting.production
      TargetFolder: $(System.DefaultWorkingDirectory)
  - task: Bash@3
    displayName: Bash Script
    inputs:
      filePath: rename.sh
      arguments: $(System.DefaultWorkingDirectory)/.env.reporting.production $(System.DefaultWorkingDirectory)/.env
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      verbose: true
      customCommand: run build --mode=production
  - task: CopyFiles@2
    displayName: 'Copy npm-built Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: dist
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true
      OverWrite: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: drop'
    inputs:
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
