export default {
  ALLFT210719811: [
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "COCO_SITK_20220810",
      Timestamp: "2022-08-10T07:36:31.357Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-08-10",
      ClientType: "ownuse",
      CreatedDatetime: "10/08/2022 19:36:26",
      DoYouFeelSafeWhereYouLive:
        "Often feel unsafe / Occasionally experience violence",
      EngagedLookingafterchildrenDays: 14,
      EngagedLookingafterchildrenFrequency: "Three or four times per week",
      EngagedOthercaregivingactivitiesDays: 16,
      EngagedOthercaregivingactivitiesFrequency: "Not at all",
      EngagedPaidWorkDays: 8,
      EngagedPaidWorkFrequency: "Three or four times per week",
      EngagedStudycollegeDays: 5,
      EngagedStudycollegeFrequency: "Less than weekly",
      EngagedVoluntaryWorkDays: 17,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 5,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_DaysInLast: 14,
      ODC1_HowMuchPerOccasion: "5",
      ODC1_MethodOfUse: "Inject",
      ODC1_OtherSubstancesConcernGambling: "Cocaine",
      ODC1_Units: "dosage (mgs)",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 84,
      PDCDaysInLast28: 3,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Less than weekly",
      Past4WkDifficultyFindingHousing: "Daily or almost daily",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Less than weekly",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 6,
      Past4WkPhysicalHealth: 4,
      Past4WkQualityOfLifeScore: 6,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 1,
      SDSIsAODUseOutOfControl: 3,
      SDS_Score: 7,
      SupportFromWhichOtherServices:
        "Other community health care service, Hospital, Medical Practitioner, Other",
      SupportTypeBestMatchesNeedsGoals:
        "Arcadia Residential Service - Non-medicated Detox Program 1 week, Althea Nurse, Primary Health Support, Supported Home Detox, Information & Education, Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Case Management, AOD counselling & support (3 - 6 sessions, then review)",
      WhenMentalHealthDiagnosis: "WithinLast3Months",
      YourCurrentHousing: "Some issues - but mostly ok"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "COCO_SITK_20220805",
      Timestamp: "2022-08-05T11:52:19.923Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "No",
      AssessmentDate: "2022-08-05",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CreatedDatetime: "05/08/2022 22:59:25",
      DoYouFeelSafeWhereYouLive:
        "Often feel unsafe / Occasionally experience violence",
      EngagedLookingafterchildrenDays: 14,
      EngagedLookingafterchildrenFrequency: "Three or four times per week",
      EngagedPaidWorkDays: 8,
      EngagedPaidWorkFrequency: "Three or four times per week",
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 6,
      HowImportantIsChangeToYou:
        "Not really important. I don't really care if I change or not",
      ODC1_AgeLastUsed: "3",
      ODC1_DaysInLast: 24,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "10-14",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 84,
      PDCDaysInLast28: 3,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Not at all",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHadCaregivingResponsibilities: "No",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Less than weekly",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 6,
      Past4WkPhysicalHealth: 6,
      Past4WkQualityOfLifeScore: 4,
      Past4WkUseLedToProblemsWithFamilyFriend: "Three or four times per week",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 1,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 8,
      SupportFromWhichOtherServices:
        "Other community health care service, Hospital",
      SupportTypeBestMatchesNeedsGoals:
        "Arcadia Residential Service - Non-medicated Detox Program 1 week, Althea Nurse",
      WhenMentalHealthDiagnosis: "MoreThan3MonthsLessThan12 months",
      YourCurrentHousing: "Some issues - but mostly ok"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "ARCA_ITSP_20220622",
      Timestamp: "2022-06-22T07:11:04.388Z",
      AreYouAccessingOtherServices: "No",
      AssessmentDate: "2022-06-22",
      ChildProtectionConcerns: "Yes",
      ClientType: "ownuse",
      CreatedDatetime: "22/06/2022 7:06:25 PM",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 3,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_DaysInLast: 13,
      ODC1_HowMuchPerOccasion: "6",
      ODC1_MethodOfUse: "Sniff (powder)",
      ODC1_OtherSubstancesConcernGambling:
        "Cannabinoids and Related Drugs, n.f.d.",
      ODC1_Units: "lines",
      PDCDaysInLast28: 2,
      PDCHowMuchPerOccassion: "4",
      PDCMethodOfUse: "Inject",
      PDCSubstanceOrGambling: "Amphetamines, n.f.d",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Less than weekly",
      Past4WkDifficultyFindingHousing: "Daily or almost daily",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Less than weekly",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 6,
      Past4WkPhysicalHealth: 4,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Daily or almost daily",
      SDSDoYouWishToStop: 2,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowDifficultToStopOrGoWithout: 3,
      SDSHowMuchDoYouWorryAboutAODUse: 1,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 9,
      SupportTypeBestMatchesNeedsGoals: "Althea Nurse, Primary Health Support"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "TSS_ITSP_20220620",
      Timestamp: "2022-06-20T08:39:06.918Z",
      AreYouCurrentlyTakingMeds: "No",
      AssessmentDate: "2022-06-20",
      ClientType: "ownuse",
      CreatedDatetime: "20/06/2022 8:30:05 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 4,
      HowSatisfiedWithProgress: "Moderately",
      ODC1_DaysInLast: 24,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "10-14",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 84,
      PDCDaysInLast28: 3,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkBeenHospCallAmbulance: "Yes",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Daily or almost daily",
      Past4WkHadCaregivingResponsibilities: "No",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Less than weekly",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Less than weekly",
      Past4WkMentalHealth: 2,
      Past4WkPhysicalHealth: 2,
      Past4WkQualityOfLifeScore: 2,
      Past4WkUseLedToProblemsWithFamilyFriend: "Three or four times per week",
      SDSDoYouWishToStop: 2,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 1,
      SDSIsAODUseOutOfControl: 2,
      SupportTypeBestMatchesNeedsGoals:
        "Arcadia Residential Service - Non-medicated Detox Program 1 week, Althea Nurse"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "PSYCHNSW_INAS_20220618",
      Timestamp: "2022-06-18T00:03:21.990Z",
      AssessmentDate: "2022-06-18",
      ClientType: "PsychoRef",
      CreatedDatetime: "18/06/2022 11:59:23 AM",
      ODC1_DaysInLast: 24,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "10-14",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 84,
      PDCDaysInLast28: 3,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 7,
      SDSDoYouWishToStop: 2,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 6
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "GOLBICE_INAS_20220406",
      Timestamp: "2022-04-05T21:46:58.193Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-04-06",
      ChildProtectionConcerns: "Yes",
      ClientType: "ownuse",
      CreatedDatetime: "06/04/2022 9:46:55 AM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedOthercaregivingactivitiesDays: 14,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 16,
      EngagedPaidWorkFrequency: "Less than weekly",
      EngagedVoluntaryWorkDays: 16,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 6,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      HowSatisfiedWithProgress: "Considerably",
      ODC1_DaysInLast: 24,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "10-14",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 84,
      PDCDaysInLast28: 3,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Three or four times per week",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHadCaregivingResponsibilities: "No",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Less than weekly",
      Past4WkHowOftenPhysicalHealthCausedProblems:
        "Three or four times per week",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Daily or almost daily",
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 1,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 5,
      SpendTime_AODSourcingUsing: " ",
      SupportFromWhichOtherServices: "Other community health care service",
      SupportTypeBestMatchesNeedsGoals: "Case Management, Althea Pharmacist",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "PSYCHACT_INAS_20220406",
      Timestamp: "2022-04-06T02:22:04.492Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-04-06",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CreatedDatetime: "06/04/2022 2:22:02 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedOthercaregivingactivitiesDays: 14,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 16,
      EngagedPaidWorkFrequency: "Less than weekly",
      EngagedVoluntaryWorkDays: 16,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 6,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      HowSatisfiedWithProgress: "Considerably",
      ODC1_DaysInLast: 24,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "10-14",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 84,
      PDCDaysInLast28: 3,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Three or four times per week",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHadCaregivingResponsibilities: "No",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Once or twice per week",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Less than weekly",
      Past4WkMentalHealth: 2,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowDifficultToStopOrGoWithout: 3,
      SDSHowMuchDoYouWorryAboutAODUse: 1,
      SDSIsAODUseOutOfControl: 2,
      SDS_Score: 11,
      SpendTime_AODSourcingUsing: " ",
      SupportFromWhichOtherServices: "Other community health care service",
      SupportTypeBestMatchesNeedsGoals: "Case Management, Althea Pharmacist",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "TSS_POTA_20220321",
      Timestamp: "2022-03-21T04:01:51.845Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-21",
      ChildProtectionConcerns: "Yes",
      ClientType: "ownuse",
      CreatedDatetime: "21/03/2022 5:01:48 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedOthercaregivingactivitiesDays: 14,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 16,
      EngagedPaidWorkFrequency: "Less than weekly",
      EngagedVoluntaryWorkDays: 16,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 6,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      HowSatisfiedWithProgress: "Considerably",
      ODC1_DaysInLast: 13,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "10-14",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 84,
      PDCDaysInLast28: 3,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Once or twice per week",
      Past4WkHowOftenPhysicalHealthCausedProblems:
        "Three or four times per week",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Once or twice per week",
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSIsAODUseOutOfControl: 1,
      SpendTime_AODSourcingUsing: " ",
      SupportFromWhichOtherServices: "Other community health care service",
      SupportTypeBestMatchesNeedsGoals: "Case Management, Althea Pharmacist",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "COCO_POTA_20220319",
      Timestamp: "2022-03-21T03:21:30.162Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-19",
      ChildProtectionConcerns: "Yes",
      ClientType: "ownuse",
      CreatedDatetime: "21/03/2022 4:21:27 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedOthercaregivingactivitiesDays: 14,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 16,
      EngagedPaidWorkFrequency: "Less than weekly",
      EngagedVoluntaryWorkDays: 16,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 6,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_DaysInLast: 13,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "10-14",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 88,
      PDCDaysInLast28: 16,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Once or twice per week",
      Past4WkHowOftenPhysicalHealthCausedProblems:
        "Three or four times per week",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Once or twice per week",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDS_Score: 8,
      SupportTypeBestMatchesNeedsGoals: "Case Management, Althea Pharmacist",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "COCO_POTA_20220317",
      Timestamp: "2022-03-17T04:00:33.486Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-17",
      ChildProtectionConcerns: "Yes",
      ClientType: "ownuse",
      CreatedDatetime: "17/03/2022 5:00:30 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedOthercaregivingactivitiesDays: 14,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 16,
      EngagedPaidWorkFrequency: "Less than weekly",
      EngagedVoluntaryWorkDays: 16,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 6,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_DaysInLast: 13,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "10-14",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 88,
      PDCDaysInLast28: 16,
      PDCHowMuchPerOccassion: "6",
      PDCMethodOfUse: "Transdermal",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Once or twice per week",
      Past4WkHowOftenPhysicalHealthCausedProblems:
        "Three or four times per week",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Once or twice per week",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 3,
      SDSHowDifficultToStopOrGoWithout: 3,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDSIsAODUseOutOfControl: 3,
      SupportTypeBestMatchesNeedsGoals: "Case Management, Althea Pharmacist",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "COCO_SITK_20220316",
      Timestamp: "2022-03-17T01:01:05.912Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-16",
      ClientType: "ownuse",
      CreatedDatetime: "17/03/2022 2:01:04 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedOthercaregivingactivitiesDays: 14,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 16,
      EngagedPaidWorkFrequency: "Less than weekly",
      HaveAnySocialSupport: "Quite a lot",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 3,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_DaysInLast: 24,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "50-59",
      ODC1_MethodOfUse: "Ingest",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 88,
      PDCDaysInLast28: 4,
      PDCMethodOfUse: "Smoke",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Not at all",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Once or twice per week",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Once or twice per week",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Once or twice per week",
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 1,
      SupportFromWhichOtherServices:
        "Other community health care service, Correctional service, Other alcohol and drug treatment service",
      SupportTypeBestMatchesNeedsGoals: "Case Management, Althea Pharmacist",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "TSS_ITSP_20220316",
      Timestamp: "2022-03-16T03:09:48.492Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-16",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CreatedDatetime: "16/03/2022 4:09:45 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedOthercaregivingactivitiesDays: 14,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 16,
      EngagedPaidWorkFrequency: "Less than weekly",
      HaveAnySocialSupport: "Quite a lot",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 3,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      HowSatisfiedWithProgress: "Slightly",
      ODC1_DaysInLast: 24,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "50-59",
      ODC1_MethodOfUse: "Ingest",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 88,
      PDCMethodOfUse: "Smoke",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      PDCUnits: "dosage (mls)",
      Past4WkBeenHospCallAmbulance: "Yes",
      Past4WkDailyLivingImpacted: "Not at all",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Once or twice per week",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Once or twice per week",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Once or twice per week",
      PrimaryCaregiver:
        "Yes - parenting responsibilities for children other than my own, No, Yes - primary caregiver: children 5 - 15 years old",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SpendTime_AODSourcingUsing: " ",
      SupportFromWhichOtherServices:
        "Other community health care service, Correctional service, Other alcohol and drug treatment service",
      SupportTypeBestMatchesNeedsGoals: "Case Management",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "TSS_undefined_20220316",
      Timestamp: "2022-03-15T23:11:50.069Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-16",
      ChildProtectionConcerns: "Yes",
      ClientType: "ownuse",
      CreatedDatetime: "16/03/2022 12:11:46 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedLookingafterchildrenDays: 27,
      EngagedLookingafterchildrenFrequency: "Daily or almost daily",
      EngagedStudycollegeDays: 17,
      EngagedStudycollegeFrequency: "Three or four times per week",
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "Quite a lot",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 6,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      HowSatisfiedWithProgress: "Slightly",
      LivingArrangement: "Alone",
      ODC1_AgeFirstUsed: 6,
      ODC1_AgeLastUsed: 66,
      ODC1_DaysInLast: 16,
      ODC1_HowMuchPerOccasion: "5",
      ODC1_MethodOfUse: "Smoke",
      ODC1_OtherSubstancesConcernGambling: "Benzodiazepines, n.f.d.",
      ODC1_Units: "dosage (mgs)",
      PDCMethodOfUse: "Ingest",
      PDCSubstanceOrGambling: "Ethanol",
      Past4WkBeenHospCallAmbulance: "No",
      Past4WkDailyLivingImpacted: "Less than weekly",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Less than weekly",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Less than weekly",
      Past4WkMentalHealth: 6,
      Past4WkPhysicalHealth: 7,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      PrimaryCaregiver:
        "Yes - primary caregiver: children under 5 years old, Yes - parenting responsibilities for children other than my own",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SpendTime_AODSourcingUsing: " ",
      SupportFromWhichOtherServices:
        "Other alcohol and drug treatment service, Mental health care service",
      SupportTypeBestMatchesNeedsGoals:
        "Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Supported home Detox",
      UsualAccommodation: "Supported accommodation facility",
      WhenMentalHealthDiagnosis: "Within last 3 months",
      YourCurrentHousing: "Stable permanent housing"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "TSS_INAS_20220313",
      Timestamp: "2022-03-16T02:26:26.407Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-13",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CountryOfBirth: "England",
      CreatedDatetime: "16/03/2022 3:26:23 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedOthercaregivingactivitiesDays: 14,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 16,
      EngagedPaidWorkFrequency: "Less than weekly",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "Quite a lot",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 3,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      HowSatisfiedWithProgress: "Slightly",
      ODC1_DaysInLast: 24,
      ODC1_Goals: "Reduce Harms",
      ODC1_HowMuchPerOccasion: "50-59",
      ODC1_MethodOfUse: "Ingest",
      ODC1_OtherSubstancesConcernGambling: "Nicotine",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 46,
      PDCAgeLastUsed: 88,
      PDCMethodOfUse: "Smoke",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      Past4WkBeenHospCallAmbulance: "Yes",
      Past4WkDailyLivingImpacted: "Not at all",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Three or four times per week",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Less than weekly",
      Past4WkMentalHealth: 6,
      Past4WkPhysicalHealth: 8,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Once or twice per week",
      PrimaryCaregiver:
        "Yes - parenting responsibilities for children other than my own, No",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SpendTime_AODSourcingUsing: " ",
      SupportFromWhichOtherServices:
        "Other community health care service, Correctional service, Other alcohol and drug treatment service",
      SupportTypeBestMatchesNeedsGoals: "Case Management",
      UsualAccommodation: "Mental health"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "TSS_INAS_20210505",
      Timestamp: "2021-05-05T02:03:45.701Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2021-05-05",
      ChildProtectionConcerns: "Yes",
      ClientType: "ownuse",
      CountryOfBirth: "7103",
      CreatedDatetime: "05/05/2021 11:52:19 AM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedVoluntaryWorkDays: 4,
      EngagedVoluntaryWorkFrequency: "Less than weekly",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 4,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      HowSatisfiedWithProgress: "Considerably",
      IndigenousStatus: "Both Aboriginal and Torres Strait Islander",
      ODC1_AgeFirstUsed: 12,
      ODC1_AgeLastUsed: 45,
      ODC1_DaysInLast: 2,
      ODC1_Goals: "Reduce Use",
      ODC1_HowMuchPerOccasion: "50-59",
      ODC1_MethodOfUse: "Transdermal",
      ODC1_OtherSubstancesConcernGambling: "Benzodiazepines, n.f.d.",
      ODC1_Units: "grams",
      PDCAgeFirstUsed: 23,
      PDCAgeLastUsed: 43,
      PDCDaysInLast28: 3,
      PDCGoals: "Maintain Current level of use",
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Gambling",
      PDCUnits: "pills",
      Past4WkBeenHospCallAmbulance: "No",
      Past4WkDailyLivingImpacted: "Less than weekly",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHadCaregivingResponsibilities: "No",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Less than weekly",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Not at all",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 6,
      Past4WkQualityOfLifeScore: 4,
      Past4WkUseLedToProblemsWithFamilyFriend: "Daily or almost daily",
      PreferredLanguage: "5203",
      SDSDoYouWishToStop: 1,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowDifficultToStopOrGoWithout: 3,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 9,
      SupportFromWhichOtherServices:
        "Other alcohol and drug treatment service, Hospital, Mental health care service",
      SupportTypeBestMatchesNeedsGoals:
        "Case Management, Primary Health Support",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "EUROPATH_INAS_20210329",
      Timestamp: "2021-03-29T04:06:11.756Z",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2021-03-29",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CreatedDatetime: "13/01/2021 14:38:19",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EngagedLookingafterchildrenDays: 8,
      EngagedLookingafterchildrenFrequency: "Once or twice per week",
      EngagedOthercaregivingactivitiesFrequency: "Not at all",
      EngagedPaidWorkDays: 28,
      EngagedPaidWorkFrequency: "Daily",
      EngagedStudycollegeFrequency: "Not at all",
      EngagedVoluntaryWorkDays: 8,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      HaveAnySocialSupport: "A wide range",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Critical for me. I need to change",
      ODC1_DaysInLast: 28,
      ODC1_HowMuchPerOccasion: "3",
      ODC1_MethodOfUse: "Ingest",
      ODC1_OtherSubstancesConcernGambling: "Alcohol",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 25,
      PDCDaysInLast28: 19,
      PDCGoals: "Cease Use",
      PDCHowMuchPerOccassion: "1",
      PDCMethodOfUse: "Inject",
      PDCSubstanceOrGambling: "Amphetamines",
      PDCUnits: "points",
      Past4WkBeenHospCallAmbulance: "Yes",
      Past4WkDailyLivingImpacted: "Daily or almost daily",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Three or four times per week",
      PrimaryCaregiver:
        "Yes - parenting responsibilities but children don't live with me, Yes - parenting responsibilities for children other than my own",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 3,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 3,
      SDS_Score: 13,
      SupportTypeBestMatchesNeedsGoals:
        "AOD counselling & support (3 - 6 sessions, then review), Case Management, Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Information & Education",
      YourCurrentHousing: "Stable permanent housing"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "EUROPATH_INAS_20210429",
      Timestamp: "2021-08-12T11:07:16.473Z",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2021-03-29",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CountryOfBirth: "India",
      CreatedDatetime: "13/01/2021 14:38:19",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EngagedLookingafterchildrenDays: 8,
      EngagedLookingafterchildrenFrequency: "Once or twice per week",
      EngagedOthercaregivingactivitiesFrequency: "Not at all",
      EngagedPaidWorkDays: 28,
      EngagedPaidWorkFrequency: "Daily",
      EngagedStudycollegeFrequency: "Not at all",
      EngagedVoluntaryWorkDays: 8,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      HaveAnySocialSupport: "A wide range",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Critical for me. I need to change",
      IndigenousStatus: "Both Aboriginal and Torres Strait Islander",
      LivingArrangement: "Alone",
      ODC1_DaysInLast: 28,
      ODC1_HowMuchPerOccasion: "3",
      ODC1_MethodOfUse: "Ingest",
      ODC1_OtherSubstancesConcernGambling: "Alcohol",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 25,
      PDCDaysInLast28: 19,
      PDCGoals: "Cease Use",
      PDCHowMuchPerOccassion: "1",
      PDCMethodOfUse: "Inject",
      PDCSubstanceOrGambling: "Amphetamines",
      PDCUnits: "points",
      Past4WkBeenHospCallAmbulance: "Yes",
      Past4WkDailyLivingImpacted: "Daily or almost daily",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Three or four times per week",
      PreferredLanguage: "French",
      PrimaryCaregiver:
        "Yes - parenting responsibilities but children don't live with me, Yes - parenting responsibilities for children other than my own",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 3,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 3,
      SDS_Score: 13,
      SupportTypeBestMatchesNeedsGoals:
        "AOD counselling & support (3 - 6 sessions, then review), Case Management, Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Information & Education",
      UsualAccommodation: "Residential aged care facility",
      YourCurrentHousing: "Stable permanent housing"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "EUROPATH_INAS_20210318",
      Timestamp: "2021-03-18T02:00:15.484Z",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2021-03-18",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CreatedDatetime: "13/01/2021 14:38:19",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EngagedLookingafterchildrenDays: 8,
      EngagedLookingafterchildrenFrequency: "Once or twice per week",
      EngagedOthercaregivingactivitiesFrequency: "Not at all",
      EngagedPaidWorkDays: 28,
      EngagedPaidWorkFrequency: "Daily",
      EngagedStudycollegeFrequency: "Not at all",
      EngagedVoluntaryWorkDays: 8,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      HaveAnySocialSupport: "A wide range",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Critical for me. I need to change",
      ODC1_DaysInLast: 28,
      ODC1_HowMuchPerOccasion: "3",
      ODC1_MethodOfUse: "Ingest",
      ODC1_OtherSubstancesConcernGambling: "Alcohol",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 25,
      PDCDaysInLast28: 19,
      PDCGoals: "Cease Use",
      PDCHowMuchPerOccassion: "1",
      PDCMethodOfUse: "Inject",
      PDCSubstanceOrGambling: "Amphetamines",
      PDCUnits: "points",
      Past4WkBeenHospCallAmbulance: "Yes",
      Past4WkDailyLivingImpacted: "Daily or almost daily",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Three or four times per week",
      PrimaryCaregiver:
        "Yes - parenting responsibilities but children don't live with me, Yes - parenting responsibilities for children other than my own",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 3,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 3,
      SDS_Score: 13,
      SupportTypeBestMatchesNeedsGoals:
        "AOD counselling & support (3 - 6 sessions, then review), Case Management, Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Information & Education",
      YourCurrentHousing: "Stable permanent housing"
    },
    {
      PartitionKey: "ALLFT210719811",
      RowKey: "COCO_INAS_20210310",
      Timestamp: "2021-03-18T01:44:09.723Z",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2021-03-10",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CreatedDatetime: "13/01/2021 14:38:19",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EngagedLookingafterchildrenDays: 8,
      EngagedLookingafterchildrenFrequency: "Once or twice per week",
      EngagedOthercaregivingactivitiesFrequency: "Not at all",
      EngagedPaidWorkDays: 28,
      EngagedPaidWorkFrequency: "Daily",
      EngagedStudycollegeFrequency: "Not at all",
      EngagedVoluntaryWorkDays: 8,
      EngagedVoluntaryWorkFrequency: "Once or twice per week",
      HaveAnySocialSupport: "A wide range",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Critical for me. I need to change",
      ODC1_DaysInLast: 28,
      ODC1_HowMuchPerOccasion: "3",
      ODC1_MethodOfUse: "Ingest",
      ODC1_OtherSubstancesConcernGambling: "Alcohol",
      ODC1_Units: "standard drinks",
      PDCAgeFirstUsed: 25,
      PDCDaysInLast28: 19,
      PDCGoals: "Cease Use",
      PDCHowMuchPerOccassion: "1",
      PDCMethodOfUse: "Inject",
      PDCSubstanceOrGambling: "Amphetamines",
      PDCUnits: "points",
      Past4WkBeenHospCallAmbulance: "Yes",
      Past4WkDailyLivingImpacted: "Daily or almost daily",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 5,
      Past4WkUseLedToProblemsWithFamilyFriend: "Three or four times per week",
      PrimaryCaregiver:
        "Yes - parenting responsibilities but children don't live with me, Yes - parenting responsibilities for children other than my own",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 3,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 3,
      SDS_Score: 13,
      SupportTypeBestMatchesNeedsGoals:
        "AOD counselling & support (3 - 6 sessions, then review), Case Management, Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Information & Education",
      YourCurrentHousing: "Stable permanent housing"
    }
  ],
  ABCTE280419831: [
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "PSYNSW_INAS_20220727",
      Timestamp: "2022-07-27T01:58:59.527Z",
      AssessmentDate: "2022-07-27",
      ClientType: "PsychiatristReferral",
      CreatedDatetime: "27/07/2022 1:58:56 PM",
      PDCMethodOfUse: "Smoke",
      PDCSubstanceOrGambling: "Pharmaceutical Opioids, n.f.d.",
      Past4WkMentalHealth: 4,
      Past4WkPhysicalHealth: 2,
      Past4WkQualityOfLifeScore: 5,
      SDSDoYouWishToStop: 2,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowDifficultToStopOrGoWithout: 1,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 9
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "PSYACT_INAS_20220619",
      Timestamp: "2022-06-18T22:14:55.845Z",
      AssessmentDate: "2022-06-19",
      ClientType: "PsychoRef",
      CreatedDatetime: "19/06/2022 10:09:34 AM",
      Past4WkMentalHealth: 2,
      Past4WkPhysicalHealth: 7,
      Past4WkQualityOfLifeScore: 7
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "ARCA_ITSP_20220310",
      Timestamp: "2022-03-09T22:52:19.290Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-10",
      ClientType: "ownuse",
      CreatedDatetime: "10/03/2022 11:52:19 AM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_HowMuchPerOccasion: "50-59",
      ODC1_MethodOfUse: "Sniff (powder)",
      ODC1_OtherSubstancesConcernGambling: "Cocaine",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Daily or almost daily",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDS_Score: 8,
      SupportTypeBestMatchesNeedsGoals:
        "AOD counselling & support (3 - 6 sessions, then review), Brief Intervention, Primary Health Support, Supported Home Detox, Arcadia House - 12 week Day Program, Althea Mental Health Nurse, Information & Education",
      YourCurrentHousing: "Homeless"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_POTA_20220310",
      Timestamp: "2022-03-09T20:49:24.430Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-10",
      ClientType: "ownuse",
      CreatedDatetime: "10/03/2022 9:49:23 AM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedLookingafterchildrenDays: 26,
      EngagedLookingafterchildrenFrequency: "Less than weekly",
      EngagedOthercaregivingactivitiesDays: 16,
      EngagedOthercaregivingactivitiesFrequency: "Once or twice per week",
      EngagedPaidWorkDays: 8,
      EngagedPaidWorkFrequency: "Daily or almost daily",
      EngagedStudycollegeDays: 14,
      EngagedStudycollegeFrequency: "Once or twice per week",
      EngagedVoluntaryWorkDays: 9,
      EngagedVoluntaryWorkFrequency: "Three or four times per week",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_HowMuchPerOccasion: "50-59",
      ODC1_MethodOfUse: "Sniff (powder)",
      ODC1_OtherSubstancesConcernGambling: "Cocaine",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "N/A",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDS_Score: 8,
      SupportTypeBestMatchesNeedsGoals:
        "AOD counselling & support (3 - 6 sessions, then review), Brief Intervention, Primary Health Support, Supported Home Detox, Arcadia House - 12 week Day Program, Althea Mental Health Nurse",
      YourCurrentHousing: "Homeless"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_SITK_20220310",
      Timestamp: "2022-03-10T03:37:22.243Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-10",
      ChildProtectionConcerns: "No",
      ClientType: "ownuse",
      CreatedDatetime: "10/03/2022 3:27:13 PM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      EngagedLookingafterchildrenDays: 18,
      EngagedLookingafterchildrenFrequency: "Daily or almost daily",
      EngagedOthercaregivingactivitiesDays: 28,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 14,
      EngagedPaidWorkFrequency: "Daily or almost daily",
      EngagedStudycollegeDays: 7,
      EngagedStudycollegeFrequency: "Once or twice per week",
      EngagedVoluntaryWorkDays: 11,
      EngagedVoluntaryWorkFrequency: "Three or four times per week",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_HowMuchPerOccasion: "50-59",
      ODC1_MethodOfUse: "Sniff (powder)",
      ODC1_OtherSubstancesConcernGambling: "Cocaine",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Daily or almost daily",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDS_Score: 8,
      SupportFromWhichOtherServices:
        "Medical Practitioner, Other community health care service, Correctional service, Hospital",
      SupportTypeBestMatchesNeedsGoals:
        "AOD counselling & support (3 - 6 sessions, then review), Brief Intervention, Primary Health Support, Supported Home Detox, Arcadia House - 12 week Day Program, Althea Mental Health Nurse, Information & Education",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "ARCA_ITSP_20220309",
      Timestamp: "2022-03-09T06:48:18.664Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-09",
      ClientType: "ownuse",
      CreatedDatetime: "09/03/2022 7:48:17 PM",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_HowMuchPerOccasion: "50-59",
      ODC1_MethodOfUse: "Sniff (powder)",
      ODC1_OtherSubstancesConcernGambling: "Cocaine",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Not at all",
      SDSDoYouWishToStop: 1,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 7,
      SupportTypeBestMatchesNeedsGoals:
        "AOD counselling & support (3 - 6 sessions, then review), Brief Intervention, Primary Health Support, Supported Home Detox",
      WhenMentalHealthDiagnosis: "WithinLast3Months",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_POTA_20220307",
      Timestamp: "2022-03-09T04:37:34.181Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-09",
      ClientType: "ownuse",
      CreatedDatetime: "09/03/2022 3:36:06 PM",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EngagedLookingafterchildrenDays: 15,
      EngagedLookingafterchildrenFrequency: "Less than weekly",
      EngagedOthercaregivingactivitiesDays: 17,
      EngagedOthercaregivingactivitiesFrequency: "Not at all",
      EngagedPaidWorkDays: 4,
      EngagedPaidWorkFrequency: "Daily or almost daily",
      EngagedStudycollegeDays: 7,
      EngagedStudycollegeFrequency: "Once or twice per week",
      EngagedVoluntaryWorkDays: 3,
      EngagedVoluntaryWorkFrequency: "Three or four times per week",
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 4,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_HowMuchPerOccasion: "20-29",
      ODC1_MethodOfUse: "Sniff (powder)",
      ODC1_OtherSubstancesConcernGambling: "Cocaine",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Three or four times per week",
      Past4WkDifficultyFindingHousing: "Daily or almost daily",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Once or twice per week",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Daily or almost daily",
      SDSDoYouWishToStop: 1,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 7,
      SpendTime_AODSourcingUsing: " ",
      SupportTypeBestMatchesNeedsGoals:
        "Althea Pharmacist, AOD counselling & support (3 - 6 sessions, then review), Information & Education, Supported Home Detox, Primary Health Support, Brief Intervention, Althea Mental Health Nurse, Arcadia House - 12 week Day Program, Arcadia Residential Service - 12 week Transition Program, Althea GP, Althea Psychologist, Althea Nurse, Arcadia Residential Service - Non-medicated Detox Program 1 week, Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Case Management",
      WhenMentalHealthDiagnosis: "WithinLast3Months",
      YourCurrentHousing: "Temporary housing / couch surfing"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_POTA_20220309",
      Timestamp: "2022-03-09T04:40:08.232Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-09",
      ClientType: "ownuse",
      CreatedDatetime: "09/03/2022 3:36:06 PM",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EngagedLookingafterchildrenDays: 15,
      EngagedLookingafterchildrenFrequency: "Less than weekly",
      EngagedOthercaregivingactivitiesDays: 17,
      EngagedOthercaregivingactivitiesFrequency: "Not at all",
      EngagedPaidWorkDays: 4,
      EngagedPaidWorkFrequency: "Daily or almost daily",
      EngagedStudycollegeDays: 7,
      EngagedStudycollegeFrequency: "Once or twice per week",
      EngagedVoluntaryWorkDays: 3,
      EngagedVoluntaryWorkFrequency: "Three or four times per week",
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns:
        "Yes - in the past 4 weeks (risk assessment required)",
      HowCloseToManagingSubstanceUse: 4,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_HowMuchPerOccasion: "20-29",
      ODC1_MethodOfUse: "Sniff (powder)",
      ODC1_OtherSubstancesConcernGambling: "Cocaine",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Three or four times per week",
      Past4WkDifficultyFindingHousing: "Daily or almost daily",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Once or twice per week",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 3,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Daily or almost daily",
      SDSDoYouWishToStop: 1,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 7,
      SpendTime_AODSourcingUsing: " ",
      SupportTypeBestMatchesNeedsGoals:
        "Althea Pharmacist, AOD counselling & support (3 - 6 sessions, then review), Information & Education, Supported Home Detox, Primary Health Support, Brief Intervention, Althea Mental Health Nurse, Arcadia House - 12 week Day Program, Arcadia Residential Service - 12 week Transition Program, Althea GP, Althea Psychologist, Althea Nurse, Arcadia Residential Service - Non-medicated Detox Program 1 week, Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Case Management",
      WhenMentalHealthDiagnosis: "WithinLast3Months",
      YourCurrentHousing: "Temporary housing / couch surfing"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "ARCA_undefined_20220308",
      Timestamp: "2022-03-09T01:33:57.987Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-08",
      ClientType: "ownuse",
      CreatedDatetime: "09/03/2022 2:33:57 PM",
      DoYouFeelSafeWhereYouLive:
        "Never feel safe / Constantly exposed to violence",
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou:
        "Not really important. I don't really care if I change or not",
      ODC1_HowMuchPerOccasion: "8",
      ODC1_MethodOfUse: "Inject",
      ODC1_OtherSubstancesConcernGambling: "Benzodiazepines, n.f.d.",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 7,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDS_Score: 8,
      SpendTime_AODSourcingUsing: " ",
      SupportTypeBestMatchesNeedsGoals:
        "Althea GP, Althea Pharmacist, Information & Education, AOD counselling & support (3 - 6 sessions, then review)",
      WhenMentalHealthDiagnosis: "WithinLast3Months",
      YourCurrentHousing: "Stable permanent housing"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_ARCA_20220308",
      Timestamp: "2022-03-08T01:26:33.714Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-08",
      CreatedDatetime: "08/03/2022 2:26:33 PM",
      DoYouFeelSafeWhereYouLive:
        "Never feel safe / Constantly exposed to violence",
      EngagedOthercaregivingactivitiesDays: 6,
      EngagedOthercaregivingactivitiesFrequency: "Three or four times per week",
      EngagedStudycollegeDays: 11,
      EngagedStudycollegeFrequency: "Three or four times per week",
      EngagedVoluntaryWorkDays: 4,
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou:
        "Not really important. I don't really care if I change or not",
      ODC1_HowMuchPerOccasion: "8",
      ODC1_MethodOfUse: "Inject",
      ODC1_OtherSubstancesConcernGambling: "Benzodiazepines, n.f.d.",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      SDSDoYouWishToStop: 2,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 3,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDS_Score: 8,
      SpendTime_AODSourcingUsing: " ",
      SupportTypeBestMatchesNeedsGoals:
        "Althea GP, Althea Pharmacist, Information & Education, AOD counselling & support (3 - 6 sessions, then review)",
      WhenMentalHealthDiagnosis: "WithinLast3Months",
      YourCurrentHousing: "Temporary housing / couch surfing"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_undefined_20220308",
      Timestamp: "2022-03-08T02:18:36.974Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-08",
      ClientType: "ownuse",
      CreatedDatetime: "08/03/2022 3:18:34 PM",
      DoYouFeelSafeWhereYouLive:
        "Never feel safe / Constantly exposed to violence",
      EngagedOthercaregivingactivitiesDays: 6,
      EngagedOthercaregivingactivitiesFrequency: "Three or four times per week",
      EngagedStudycollegeDays: 11,
      EngagedStudycollegeFrequency: "Three or four times per week",
      EngagedVoluntaryWorkDays: 4,
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou:
        "Not really important. I don't really care if I change or not",
      ODC1_HowMuchPerOccasion: "8",
      ODC1_MethodOfUse: "Inject",
      ODC1_OtherSubstancesConcernGambling: "Benzodiazepines, n.f.d.",
      ODC1_Units: "grams",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Once or twice per week",
      Past4WkDifficultyFindingHousing: "Less than weekly",
      Past4WkHaveYouViolenceAbusive: "Yes (risk assessment required)",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Less than weekly",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDS_Score: 8,
      SpendTime_AODSourcingUsing: " ",
      SupportTypeBestMatchesNeedsGoals:
        "Althea GP, Althea Pharmacist, Information & Education, AOD counselling & support (3 - 6 sessions, then review)",
      WhenMentalHealthDiagnosis: "WithinLast3Months",
      YourCurrentHousing: "Temporary housing / couch surfing"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_ARCA_20220304",
      Timestamp: "2022-03-04T04:52:59.483Z",
      AreYouAccessingOtherServices: "No",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2022-03-04",
      ClientType: "ownuse",
      CreatedDatetime: "04/03/2022 5:52:57 PM",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EngagedOthercaregivingactivitiesDays: 6,
      EngagedOthercaregivingactivitiesFrequency: "Three or four times per week",
      EngagedStudycollegeDays: 11,
      EngagedStudycollegeFrequency: "Three or four times per week",
      EngagedVoluntaryWorkDays: 4,
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Less than weekly",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Not at all",
      SDSDoYouWishToStop: 2,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowDifficultToStopOrGoWithout: 3,
      SDSHowMuchDoYouWorryAboutAODUse: 1,
      SDS_Score: 8,
      SpendTime_AODSourcingUsing: " ",
      SupportTypeBestMatchesNeedsGoals: "Althea GP",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_ARCA_20210824",
      Timestamp: "2022-03-04T04:28:13.005Z",
      AreYouAccessingOtherServices: "No",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2021-08-24",
      ClientType: "ownuse",
      CreatedDatetime: "04/03/2022 5:28:10 PM",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EverDiagnosedMentalHealthIssue: "No",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Less than weekly",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Not at all",
      SDSDoYouWishToStop: 1,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 7,
      SpendTime_AODSourcingUsing: " ",
      SupportTypeBestMatchesNeedsGoals: "Arcadia House - 12 week Day Program",
      YourCurrentHousing: "At risk of eviction"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "COCO_SITK_20210824",
      Timestamp: "2022-03-10T23:02:18.277Z",
      AreYouAccessingOtherServices: "Yes",
      AreYouCurrentlyTakingMeds: "Yes",
      AssessmentDate: "2021-08-24",
      ChildProtectionConcerns: "Yes",
      ClientType: "ownuse",
      CreatedDatetime: "11/03/2022 12:02:16 PM",
      DoYouFeelSafeWhereYouLive: "Yes - Completely safe",
      EngagedLookingafterchildrenDays: 3,
      EngagedLookingafterchildrenFrequency: "Not at all",
      EngagedOthercaregivingactivitiesDays: 13,
      EngagedOthercaregivingactivitiesFrequency: "Daily or almost daily",
      EngagedPaidWorkDays: 9,
      EngagedPaidWorkFrequency: "Daily or almost daily",
      EngagedStudycollegeDays: 4,
      EngagedStudycollegeFrequency: "Once or twice per week",
      EngagedVoluntaryWorkDays: 7,
      EngagedVoluntaryWorkFrequency: "Three or four times per week",
      EverDiagnosedMentalHealthIssue: "Yes",
      HaveAnySocialSupport: "A few",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      ODC1_HowMuchPerOccasion: "30-39",
      ODC1_MethodOfUse: "Sniff (powder)",
      ODC1_OtherSubstancesConcernGambling: "Ethanol",
      ODC1_Units: "points",
      PDCDaysInLast28: 11,
      PDCHowMuchPerOccassion: "9",
      PDCMethodOfUse: "Other",
      PDCSubstanceOrGambling: "Nicotine",
      PDCUnits: "grams",
      Past4WkDailyLivingImpacted: "Three or four times per week",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHadCaregivingResponsibilities: "Yes",
      Past4WkHaveYouViolenceAbusive: "No",
      Past4WkHowOftenMentalHealthCausedProblems: "Daily or almost daily",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 7,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 7,
      Past4WkUseLedToProblemsWithFamilyFriend: "Daily or almost daily",
      SDSDoYouWishToStop: 1,
      SDSDoesMissingFixMakeAnxious: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 3,
      SDSIsAODUseOutOfControl: 1,
      SDS_Score: 7,
      SupportFromWhichOtherServices:
        "Other community health care service, Medical Practitioner, Mental health care service, Correctional service, Other",
      SupportTypeBestMatchesNeedsGoals:
        "Information & Education, Brief Intervention, AOD counselling & support (3 - 6 sessions, then review), Group participation - ADAPT / SMART Recovery / COMPASS / Butt it Out, Case Management, Althea Mental Health Nurse, Althea Pharmacist, Supported Home Detox, Arcadia House - 12 week Day Program",
      WhenMentalHealthDiagnosis: "WithinLast3Months",
      YourCurrentHousing: "Temporary housing / couch surfing"
    },
    {
      PartitionKey: "ABCTE280419831",
      RowKey: "TSS_ITSP_20210729",
      Timestamp: "2021-07-28T22:18:32.056Z",
      AssessmentDate: "2021-07-29",
      ClientType: "ownuse",
      CreatedDatetime: "29/07/2021 10:18:28 AM",
      DoYouFeelSafeWhereYouLive: "Mostly safe. Sometimes feel threatened",
      HaveAnySocialSupport: "Some",
      HaveDVOrFamilySafetyConcerns: "No",
      HowCloseToManagingSubstanceUse: 8,
      HowImportantIsChangeToYou: "Really important. I'd like to change",
      HowSatisfiedWithProgress: "Moderately",
      PDCMethodOfUse: "Smoke",
      PDCSubstanceOrGambling: "Benzodiazepines, n.f.d.",
      Past4WkDailyLivingImpacted: "Not at all",
      Past4WkDifficultyFindingHousing: "Not at all",
      Past4WkHowOftenMentalHealthCausedProblems: "Not at all",
      Past4WkHowOftenPhysicalHealthCausedProblems: "Daily or almost daily",
      Past4WkMentalHealth: 5,
      Past4WkPhysicalHealth: 5,
      Past4WkQualityOfLifeScore: 6,
      Past4WkUseLedToProblemsWithFamilyFriend: "Not at all",
      SDSDoYouWishToStop: 3,
      SDSDoesMissingFixMakeAnxious: 1,
      SDSHowDifficultToStopOrGoWithout: 2,
      SDSHowMuchDoYouWorryAboutAODUse: 2,
      SDS_Score: 8,
      YourCurrentHousing: "Some issues - but mostly ok"
    }
  ]
};
